### PR TITLE
fork.java Class | Uploaded File!

### PR DESCRIPTION
**Pull request by 1NoobMaster1**
This file has been uploaded to check how folk in GitHub Works.

### CODE REVIEW

**Comment by 1NoobMaster1** [comment]
Woow!

**Comment by 1NoobMaster1** [comment]
> This file has been uploaded to check how folk in GitHub Works.

Great Work!

**Comment by CC-Jitters** [comment]
Nice!

**Comment by CC-Jitters** [comment]
> This file has been uploaded to check how folk in GitHub Works.

Awesome!

**Pull request merged**
